name: Deploy Dockerized FastAPI App

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: mirzahaiderocloud/cicd-example

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add DB url to .env
      run: |
        echo DATABASE_URL=${{ secrets.DB_ENDPOINT }} >> .env

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ github.sha }}
          
    - name: Deploy via SSH
      run: |
        echo "${{ secrets.EC2_KEY }}" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem "${{secrets.EC2_USER}}"@"${{secrets.EC2_HOST}}" << 'EOF'

        sudo docker stop cicd-example || true
        sudo docker rm cicd-example || true

        sudo docker pull ${{ env.IMAGE_NAME }}
        sudo docker run -d --name cicd-example -p 80:80 ${{ env.IMAGE_NAME }}
        EOF
