name: Deploy Dockerized FastAPI App

on:
  workflow_dispatch:
  push:
    branches:
      - main

# secrets: EC2_KEY, EC2_USER, EC2_HOST, DB_ENDPOINT

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        echo "${{ secrets.EC2_KEY }}" > github-ec2.pem && chmod 600 github-ec2.pem

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem "${{secrets.EC2_USER}}"@"${{secrets.EC2_HOST}}" << 'EOF'

        REPO="https://github.com/mirza-haider-ocloud/cicd-example.git"
        TARGET_DIR="/home/ubuntu/cicd-example"
        
        if [ -d "$TARGET_DIR/.git" ]; then
          echo "Directory exists — pulling latest changes"
          cd "$TARGET_DIR"
          git pull origin main
        else
          echo "Directory does not exist — cloning repository"
          git clone "$REPO" "$TARGET_DIR"
        fi

        cd "$TARGET_DIR"
        echo DATABASE_URL=${{ secrets.DB_ENDPOINT }} >> .env

        sudo docker stop fastapi-app || true
        sudo docker rm fastapi-app || true

        sudo docker build -t fastapi-app .
        sudo docker run -d --name fastapi-app -p 80:80 fastapi-app
        EOF
